NAME = coremark-am
APP = /home/nmy/ics2019/nexus-am/apps/coremark/build/coremark-x86-navy
OBJS = /home/nmy/ics2019/nexus-am/apps/coremark/build/x86-navy//./src/core_list_join.o /home/nmy/ics2019/nexus-am/apps/coremark/build/x86-navy//./src/core_util.o /home/nmy/ics2019/nexus-am/apps/coremark/build/x86-navy//./src/core_state.o /home/nmy/ics2019/nexus-am/apps/coremark/build/x86-navy//./src/core_matrix.o /home/nmy/ics2019/nexus-am/apps/coremark/build/x86-navy//./src/core_main.o /home/nmy/ics2019/nexus-am/apps/coremark/build/x86-navy//./src/core_portme.o /home/nmy/ics2019/nexus-am/am/build/am-x86-navy.a /home/nmy/ics2019/nexus-am/libs/klib/build/klib-x86-navy.a
LIBS += libndl
include /home/nmy/ics2019/navy-apps/Makefile.app
